version: '3.7'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
